language:
  - c

before_install:
 - sudo apt-get install libudns-dev libgsasl7-dev libpostgresql-ocaml-dev

script:
 - autoreconf -vfi && ./configure --enable-pgsql --enable-pipe --enable-debug --enable-ssl && make
